Repository feed-the-people/Back-End, pull requests merged in 2021-01, with the labels that each got.

#25 UserRecipe Resource
  app/models/recipe.rb
  app/models/user_recipe.rb
  db/migrate/20210104164027_create_user_recipe.rb
  db/schema.rb
  spec/factories/user_recipes.rb
  spec/models/recipe_spec.rb
  spec/models/user_recipe_spec.rb
  spec/models/user_spec.rb
Labels: priority 1 🚨, setup 🛠

#27 Remove billing info
  app/graphql/types/user_type.rb
  db/migrate/20210104181526_remove_billing_info_from_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/queries/users/get_user_spec.rb
Labels: priority 2 🔨

#30 Average Rating for Recipe
  db/migrate/20210104183527_add_avg_rating_to_recipe.rb
  db/schema.rb
Labels: priority 2 🔨, setup 🛠

#37 Create user recipe
  app/graphql/mutations/user_recipes/create_user_recipe.rb
  app/graphql/types/input/user_recipes/create_input_type.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/user_recipe_type.rb
  app/models/recipe.rb
  spec/models/recipe_spec.rb
  spec/rails_helper.rb
  spec/requests/mutations/user_recipes/create_user_recipe_spec.rb
  spec/requests/queries/users/get_user_spec.rb
Labels: API 🖋, MVP, Mutation 🧟

#38 allRecipes API Call
  .DS_Store
  .gitignore
  app/graphql/queries/base_query.rb
  app/graphql/queries/recipes/all_recipes.rb
  app/graphql/types/query_type.rb
  app/graphql/types/recipe_type.rb
  app/models/recipe.rb
  db/migrate/20210105184601_add_charity_name_to_recipe.rb
  db/schema.rb
  spec/factories/recipes.rb
  spec/models/recipe_spec.rb
  spec/requests/queries/recipes/all_recepies_spec.rb
Labels: API 🖋, MVP, Query 🎁

#54 createIngredient API Call
  app/graphql/mutations/ingredients/create_ingredient.rb
  app/graphql/types/input/ingredients/ingredient_input_type.rb
  app/graphql/types/mutation_type.rb
  spec/requests/mutations/ingredients/create_ingredient_spec.rb
Labels: API 🖋, MVP, Mutation 🧟

#58 createRecipe API Mutation
  app/graphql/mutations/recipes/create_recipe.rb
  app/graphql/types/input/recipes/recipe_ingredient_type.rb
  app/graphql/types/input/recipes/recipe_input_type.rb
  app/graphql/types/mutation_type.rb
  spec/requests/mutations/recipes/create_recipe_spec.rb
Labels: API 🖋, MVP, Mutation 🧟

#64 Update Seeds
  app/graphql/types/input/recipes/recipe_input_type.rb
  db/migrate/20210108183254_change_charity_id_to_string.rb
  db/schema.rb
  db/seeds.rb
  spec/requests/mutations/recipes/create_recipe_spec.rb
Labels: setup 🛠

#67 Bug Fix: Recipe
  app/models/recipe.rb
  spec/models/recipe_spec.rb
  spec/requests/mutations/user_recipes/update_rating_spec.rb
Labels: API 🖋, bug fix 🐛

#72 Add image to recipe
  README.md
  app/graphql/mutations/recipes/create_recipe.rb
  app/graphql/types/input/recipes/recipe_input_type.rb
  spec/requests/mutations/recipes/create_recipe_spec.rb
Labels: API 🖋, bug fix 🐛
